
language: python
sudo: required
dist: xenial

python:
  - "3.7"
  
env:
  matrix:
  - VFBPDB=pdb.virtualflybrain.org 
    RUNTESTS='vfb_query_builder.test.results_schema_tests vfb_query_builder.test.TermInfo_schema_tests vfb_query_builder.test.query_roller_tests'
  - VFBPDB=pdb-alpha.virtualflybrain.org
    RUNTESTS='vfb_query_builder.test.results_schema_tests vfb_query_builder.test.TermInfo_schema_tests'
  - VFBPDB=pdb-dev.virtualflybrain.org
    RUNTESTS='vfb_query_builder.test.results_schema_tests vfb_query_builder.test.TermInfo_schema_tests vfb_query_builder.test.query_roller_tests'

install:
  - pip install -r requirements.txt
  
before_script:
  - git clone https://github.com/VirtualFlyBrain/VFB_neo4j.git

script:
  - sed -i "s|neo4j_connect('http://.*\.virtualflybrain\.org', 'neo4j', 'neo4j')|neo4j_connect('http://$VFBPDB', 'neo4j', 'neo4j')|g" $TRAVIS_BUILD_DIR/src/vfb_query_builder/test/test_tools.py
  - grep -r '= neo4j_connect(' .
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/src/:$(pwd)/VFB_neo4j/src/
  - cd src
  - |
    for TEST in $RUNTESTS;
    do
      /bin/echo -e "\e[1;35mRunning $TEST\e[0m" > log.log;
      python -m $TEST >> log.log;
      /bin/sed -i s/FAIL/\\e\[1\;31mFAIL\\e\[0m/g log.log;
      /bin/sed -i s/Validation\ Passes/\\e\[1\;32mValidation\ Passes\\e\[0m/g log.log;
      cat log.log;
      if grep -q FAIL "$File"; 
      then 
        exit 1;
      fi;
    done;

