
language: python
sudo: required
dist: xenial

python:
  - "3.7"
  
env:
  matrix:
  - VFBPDB=pdb.virtualflybrain.org
  - VFBPDB=pdb-alpha.virtualflybrain.org
  - VFBPDB=pdb-dev.virtualflybrain.org

install:
  - pip install -r requirements.txt
  
before_script:
  - git clone https://github.com/VirtualFlyBrain/VFB_neo4j.git

script:
  - sed -i s|neo4j_connect('http://.*\.virtualflybrain\.org', 'neo4j', 'neo4j')|neo4j_connect('http://$VFBPDB', 'neo4j', 'neo4j')|g $TRAVIS_BUILD_DIR/src/test/query_roller_tests.py
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/src/:$(pwd)/VFB_neo4j/src/
  - cd src
  - python -m vfb_query_builder.test.results_schema_tests
  - python -m vfb_query_builder.test.TermInfo_schema_tests

