language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  - git clone git@github.com:VirtualFlyBrain/VFB_neo4j.git
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/src/:VFB_neo4j/src/
  - python src/test/query_roller_tests.py
